services:
  postgres:
    image: postgres:16

    container_name: cx-postgres

    environment:
      POSTGRES_USER: cx_admin
      POSTGRES_PASSWORD: cx_password
      POSTGRES_DB: cx_analytics

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
